### ISSUE TITLE
Improve project make

### ISSUE THREAD

**Issue by ghost** [KostiaShrubenko/cryptfile#1]
Please improve project build:
1. Add dependencies as a submodules or include copy of libraries which is used into your source tree 
2. Create Make or CMake file in root of your project which will build final executable
finally it must be possible to build project using a single (or 2 in case of CMake) from the root of your project. That command must build all required dependencies and your code.

**Comment by KostiaShrubenko** [comment]
The project structure was a bit redesigned. Now you are able to compile my project with one Makefile.
