### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by ghost** [KostiaShrubenko/cryptfile#2]
```
cryptfile$ make --version
GNU Make 4.2.1
Built for x86_64-pc-linux-gnu
Copyright (C) 1988-2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
cryptfile$ make 
clean    install  src/     
andriy@ringpad:~/Projects/tmp/cryptfile$ make install 
gcc -std=c99 -I".\extramodules\libtomcrypt\src\headers" -I".\src\cypher\inc" -I".\src\interface\inc" -I".\src\header\inc" -I".\src" -c src/cryptfile.c -o src/cryptfile.o
In file included from src/cryptfile.c:1:
src/cryptfile.h:9:10: fatal error: interface.h: No such file or directory
    9 | #include "interface.h"
      |          ^~~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:33: src/cryptfile.o] Error 1

```

**Comment by KostiaShrubenko** [comment]
Note that the makefile which you used was designed for a MinGW environment and gmake + gcc.

I added a new makefile which is called "Makefile.unix". You should use it as follows: 
"**make -f Makefile.unix install**"
Actually, I am not sure if it can compile the project since I don't have the means to test it.

**Comment by KostiaShrubenko** [comment]
@andriyohorodnyk 
Eventually, I decided to launch Linux on a virtual machine. Thus I was able to test "Makefile.unix" so it compiled with success. 
Also, I made a few minor changes to source files to accept paths in the Unix style with the folder separator '/'.

**Comment by KostiaShrubenko** [comment]
@andriyohorodnyk did it compile on your machine well? Can I close that issue?
